### ISSUE TITLE
ValueError from _extrapolate_rows

### ISSUE THREAD

**Issue by duncanwp** [pytroll/python-geotiepoints#2]
I've just come across this project and it looks exactly what I was after, but I'm getting an error when doing the interpolation. I've checked out the code and unit tests are failing with the same problem. 

For example `tests.test_geointerpolator.test_fill_row_borders` fails with:

```
Error
Traceback (most recent call last):
  File "/Users/watson-parris/miniconda3/envs/cis_dev/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/watson-parris/PycharmProjects/python-geotiepoints/tests/test_geointerpolator.py", line 137, in test_fill_row_borders
    satint._fill_row_borders()
  File "/Users/watson-parris/PycharmProjects/python-geotiepoints/geotiepoints/interpolator.py", line 222, in _fill_row_borders
    self.hrow_indices[index + chunk_size - 1])
  File "/Users/watson-parris/PycharmProjects/python-geotiepoints/geotiepoints/interpolator.py", line 186, in _extrapolate_rows
    pos = row_indices[:2]
ValueError: cannot slice a 0-d array
```

and the `tests.test_geointerpolator.test_extrapolate_rows` test fails with:

```
Error
Traceback (most recent call last):
  File "/Users/watson-parris/miniconda3/envs/cis_dev/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/watson-parris/PycharmProjects/python-geotiepoints/tests/test_geointerpolator.py", line 119, in test_extrapolate_rows
    self.assertTrue(np.allclose(satint._extrapolate_rows(satint.tie_data[0]),
TypeError: _extrapolate_rows() takes exactly 5 arguments (2 given)
```

Did you perhaps not push all the changes when you made the last commit? 

Thanks

**Comment by adybbroe** [comment]
Can you please test again @duncanwp ?
It should be fixed now, I hope.

**Comment by adybbroe** [comment]
@duncanwp Can we close this?

-Adam

**Comment by duncanwp** [comment]
Sorry, yes this is fixed now.
